#!/usr/bin/env python3
"""
Central constants for InkBurn extension.

This module consolidates all configuration constants used across the InkBurn
extension to ensure consistency and make maintenance easier.
"""

# =============================================================================
# XML/SVG Namespaces
# =============================================================================

NS = {
    'svg': 'http://www.w3.org/2000/svg',
    'inkscape': 'http://www.inkscape.org/namespaces/inkscape'
}

INKSCAPE_NS = "http://www.inkscape.org/namespaces/inkscape"


# =============================================================================
# G-Code Generation
# =============================================================================

SMAX = 1000              # Maximum laser power (S value)
TRAVEL_SPEED = 4000      # mm/min for travel moves (G0)
COORD_PRECISION = 2      # Decimal precision for coordinate output
GCODE_SEPARATOR = ''     # Separator between G-code command parts


# =============================================================================
# Path Processing
# =============================================================================

CURVE_PRECISION = 0.1    # mm per interpolation step for curve subdivision
CLOSED_PATH_TOLERANCE = 0.01  # Distance threshold to consider a path closed (mm)


# =============================================================================
# G-Code Templates
# =============================================================================

HEADER_GCODE = [
    '; Generated by Ink/Burn GCode Export',
    'G21 ; units mm',
    'G90 ; absolute coords',
    f'G0 F{TRAVEL_SPEED} ; set travel speed',
    'M4  ; laser on'
]

FOOTER_GCODE = [
    'M5 ; laser off',
    'G0 X0 Y0 ; return to origin',
    'M2 ; end program'
]
