"""Tests for G-code generator output format."""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest
from inkex.transforms import Vector2d

from gcode.generator import GCodeGenerator
from models.job import Job, JobType
from models.layer import Layer
from models.machine import MachineSettings
from models.path import PathSegment, PathType


class TestGCodeHeader:
    """G-code header format tests."""

    def test_header_contains_required_lines(self) -> None:
        """Header must include spec-required comment and commands."""
        gen = GCodeGenerator()
        gen.add_header(document_name="test_file")
        output = gen.get_gcode()
        assert "; Generated by Inkscape InkBurn extension" in output
        assert "; Document: test_file" in output
        assert "; Date:" in output
        assert "G21" in output
        assert "G90" in output

    def test_footer_has_m5_and_return(self) -> None:
        """Footer must include M5 and return to origin."""
        gen = GCodeGenerator()
        gen.add_footer()
        output = gen.get_gcode()
        assert "M5" in output
        assert "G0 X0 Y0" in output


class TestGCodeComments:
    """G-code comment insertion tests."""

    def _make_segment(self, points: list[tuple[float, float]]) -> PathSegment:
        """Helper to create a PathSegment."""
        return PathSegment(
            points=[Vector2d(*p) for p in points],
            element_id="rect42",
            element_type="rect",
        )

    def test_layer_comment(self) -> None:
        """Layer processing adds layer comment."""
        gen = GCodeGenerator()
        gen.add_comment("Layer: Cutting Layer")
        output = gen.get_gcode()
        assert "; Layer: Cutting Layer" in output

    def test_job_comment(self) -> None:
        """Job processing adds job comment with type and id."""
        gen = GCodeGenerator()
        job = Job.create_default(JobType.CUT)
        seg = self._make_segment([(0, 0), (10, 0)])
        gen.add_job([seg], job, 0)
        output = gen.get_gcode()
        assert "; Job: cut 0" in output
        assert f"id={job.id}" in output

    def test_shape_comment(self) -> None:
        """Shape comment includes element type and id."""
        gen = GCodeGenerator()
        seg = self._make_segment([(0, 0), (10, 0)])
        gen.add_shape_comment(seg)
        output = gen.get_gcode()
        assert "; Shape: rect#rect42" in output


class TestGCodePowerClamping:
    """Power and speed clamping tests."""

    def test_power_exceeding_max_is_clamped(self) -> None:
        """Power above machine max is clamped and logged."""
        settings = MachineSettings(max_power=500)
        gen = GCodeGenerator(settings)
        job = Job.create_default(JobType.CUT)
        job.power_max = 1000.0

        seg = PathSegment(
            points=[Vector2d(0, 0), Vector2d(10, 0)],
            element_id="test",
            element_type="path",
        )
        gen.add_segment(seg, job)
        output = gen.get_gcode()
        assert "S500" in output
        assert "S1000" not in output

    def test_speed_within_range(self) -> None:
        """Speed within machine range is not clamped."""
        settings = MachineSettings(max_speed=6000)
        gen = GCodeGenerator(settings)
        job = Job.create_default(JobType.CUT)
        job.speed = 3000.0

        seg = PathSegment(
            points=[Vector2d(0, 0), Vector2d(10, 0)],
            element_id="test",
            element_type="path",
        )
        gen.add_segment(seg, job)
        output = gen.get_gcode()
        assert "F3000" in output


class TestGCodeDuplicateSuppression:
    """Duplicate coordinate and command suppression."""

    def test_no_duplicate_coordinates(self) -> None:
        """Moving to the same point twice does not emit a second line."""
        gen = GCodeGenerator()
        p = Vector2d(5.0, 5.0)
        gen.move_to(p, is_cutting=False)
        gen.move_to(p, is_cutting=False)
        lines = [l for l in gen.get_gcode().split("\n") if l.strip()]
        coord_lines = [l for l in lines if "X5" in l and "Y5" in l]
        assert len(coord_lines) == 1

    def test_invisible_layer_skipped(self) -> None:
        """Invisible layer produces no G-code."""
        gen = GCodeGenerator()
        layer = Layer(layer_id="L1", label="Hidden", visible=False)
        layer.add_job(JobType.CUT)
        seg = PathSegment(
            points=[Vector2d(0, 0), Vector2d(10, 0)],
            element_id="test",
            element_type="path",
        )
        assert gen.get_gcode().strip() == ""
