"""Tests for G-code generator output format."""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest
from inkex.transforms import Vector2d
from lxml import etree

from export_layers import _fill_power
from gcode.generator import GCodeGenerator
from models.job import Job, JobType
from models.layer import Layer
from models.machine import MachineSettings
from models.path import PathSegment, PathType


class TestFillPowerColorMapping:
    """Fill color to laser power mapping."""

    def _element_with_fill(self, fill: str) -> etree._Element:
        """Create a minimal element with a fill style."""
        elem = etree.Element("path")
        elem.set("style", f"fill:{fill}")
        return elem

    def test_black_fill_uses_power_max(self) -> None:
        """Black fill maps to maximum power."""
        job = Job.create_default(JobType.FILL)
        job.power_min = 100.0
        job.power_max = 900.0
        assert _fill_power(
            self._element_with_fill("#000000"), job
        ) == pytest.approx(900.0)

    def test_white_fill_uses_power_min(self) -> None:
        """White fill maps to minimum power."""
        job = Job.create_default(JobType.FILL)
        job.power_min = 100.0
        job.power_max = 900.0
        assert _fill_power(
            self._element_with_fill("#ffffff"), job
        ) == pytest.approx(100.0)

    def test_mid_fill_uses_intermediate_power(self) -> None:
        """Intermediate luminance maps inside the power range."""
        job = Job.create_default(JobType.FILL)
        job.power_min = 100.0
        job.power_max = 900.0
        power = _fill_power(self._element_with_fill("rgb(128,128,128)"), job)
        assert 100.0 < power < 900.0

    def test_named_fill_is_calculated_by_parser(self) -> None:
        """Named CSS colors are parsed without a local lookup table."""
        job = Job.create_default(JobType.FILL)
        job.power_min = 0.0
        job.power_max = 1000.0
        power = _fill_power(self._element_with_fill("white"), job)
        assert power == pytest.approx(0.0)

    def test_linear_gradient_samples_at_point(self) -> None:
        """Gradient fill power depends on the hatch point location."""
        job = Job.create_default(JobType.FILL)
        job.power_min = 100.0
        job.power_max = 900.0

        svg = etree.Element("svg")
        gradient = etree.SubElement(svg, "linearGradient", id="grad")
        etree.SubElement(
            gradient,
            "stop",
            offset="0%",
            style="stop-color:#000000",
        )
        etree.SubElement(
            gradient,
            "stop",
            offset="100%",
            style="stop-color:#ffffff",
        )
        shape = etree.SubElement(svg, "path")
        shape.set("style", "fill:url(#grad)")

        bbox = (0.0, 0.0, 10.0, 10.0)
        dark_power = _fill_power(shape, job, Vector2d(0, 10), 10.0, bbox)
        light_power = _fill_power(shape, job, Vector2d(10, 10), 10.0, bbox)
        mid_power = _fill_power(shape, job, Vector2d(5, 10), 10.0, bbox)

        assert dark_power == pytest.approx(900.0)
        assert light_power == pytest.approx(100.0)
        assert 100.0 < mid_power < 900.0


class TestGCodeHeader:
    """G-code header format tests."""

    def test_header_contains_required_lines(self) -> None:
        """Header must include spec-required comment and commands."""
        gen = GCodeGenerator()
        gen.add_header(document_name="test_file")
        output = gen.get_gcode()
        assert "; Generated by Inkscape InkBurn extension" in output
        assert "; Document: test_file" in output
        assert "; Date:" in output
        assert "G21" in output
        assert "G90" in output

    def test_footer_has_m5_and_return(self) -> None:
        """Footer must include M5 and return to origin."""
        gen = GCodeGenerator()
        gen.add_footer()
        output = gen.get_gcode()
        assert "M5" in output
        assert "G0 X0 Y0" in output


class TestGCodeComments:
    """G-code comment insertion tests."""

    def _make_segment(self, points: list[tuple[float, float]]) -> PathSegment:
        """Helper to create a PathSegment."""
        return PathSegment(
            points=[Vector2d(*p) for p in points],
            element_id="rect42",
            element_type="rect",
        )

    def test_layer_comment(self) -> None:
        """Layer processing adds layer comment."""
        gen = GCodeGenerator()
        gen.add_comment("Layer: Cutting Layer")
        output = gen.get_gcode()
        assert "; Layer: Cutting Layer" in output

    def test_job_comment(self) -> None:
        """Job processing adds job comment with type and id."""
        gen = GCodeGenerator()
        job = Job.create_default(JobType.CUT)
        seg = self._make_segment([(0, 0), (10, 0)])
        gen.add_job([seg], job, 0)
        output = gen.get_gcode()
        assert "; Job: cut 0" in output
        assert f"id={job.id}" in output

    def test_shape_comment(self) -> None:
        """Shape comment includes element type and id."""
        gen = GCodeGenerator()
        seg = self._make_segment([(0, 0), (10, 0)])
        gen.add_shape_comment(seg)
        output = gen.get_gcode()
        assert "; Shape: rect#rect42" in output


class TestGCodePowerClamping:
    """Power and speed clamping tests."""

    def test_power_exceeding_max_is_clamped(self) -> None:
        """Power above machine max is clamped and logged."""
        settings = MachineSettings(max_power=500)
        gen = GCodeGenerator(settings)
        job = Job.create_default(JobType.CUT)
        job.power_max = 1000.0

        seg = PathSegment(
            points=[Vector2d(0, 0), Vector2d(10, 0)],
            element_id="test",
            element_type="path",
        )
        gen.add_segment(seg, job)
        output = gen.get_gcode()
        assert "S500" in output
        assert "S1000" not in output

    def test_segment_power_overrides_job_power(self) -> None:
        """Per-segment power is emitted when present."""
        gen = GCodeGenerator()
        job = Job.create_default(JobType.FILL)
        job.power_max = 1000.0

        seg = PathSegment(
            points=[Vector2d(0, 0), Vector2d(10, 0)],
            element_id="test",
            element_type="hatch",
            power=250.0,
        )
        gen.add_segment(seg, job)
        output = gen.get_gcode()
        assert "S250" in output
        assert "S1000" not in output

    def test_segment_powers_emit_power_changes(self) -> None:
        """Per-point power values are emitted along a segment."""
        gen = GCodeGenerator()
        job = Job.create_default(JobType.FILL)
        job.power_max = 1000.0

        seg = PathSegment(
            points=[Vector2d(0, 0), Vector2d(5, 0), Vector2d(10, 0)],
            element_id="test",
            element_type="hatch",
            powers=[100.0, 500.0, 900.0],
        )
        gen.add_segment(seg, job)
        output = gen.get_gcode()
        assert "M3 S100" in output
        assert "S500" in output
        assert "S900" in output

    def test_speed_within_range(self) -> None:
        """Speed within machine range is not clamped."""
        settings = MachineSettings(max_speed=6000)
        gen = GCodeGenerator(settings)
        job = Job.create_default(JobType.CUT)
        job.speed = 3000.0

        seg = PathSegment(
            points=[Vector2d(0, 0), Vector2d(10, 0)],
            element_id="test",
            element_type="path",
        )
        gen.add_segment(seg, job)
        output = gen.get_gcode()
        assert "F3000" in output


class TestGCodeDuplicateSuppression:
    """Duplicate coordinate and command suppression."""

    def test_no_duplicate_coordinates(self) -> None:
        """Moving to the same point twice does not emit a second line."""
        gen = GCodeGenerator()
        p = Vector2d(5.0, 5.0)
        gen.move_to(p, is_cutting=False)
        gen.move_to(p, is_cutting=False)
        lines = [l for l in gen.get_gcode().split("\n") if l.strip()]
        coord_lines = [l for l in lines if "X5" in l and "Y5" in l]
        assert len(coord_lines) == 1

    def test_invisible_layer_skipped(self) -> None:
        """Invisible layer produces no G-code."""
        gen = GCodeGenerator()
        layer = Layer(layer_id="L1", label="Hidden", visible=False)
        layer.add_job(JobType.CUT)
        seg = PathSegment(
            points=[Vector2d(0, 0), Vector2d(10, 0)],
            element_id="test",
            element_type="path",
        )
        assert gen.get_gcode().strip() == ""
