"""G-code generator for InkBurn extension.

Produces clean GRBL 1.1 G-code with state tracking to suppress redundant
commands and coordinates.
"""

import logging
from datetime import datetime, timezone
from typing import List, Optional

from inkex.transforms import Vector2d

from constants import COORD_PRECISION, TRAVEL_SPEED
from models.job import Job, JobType
from models.layer import Layer
from models.machine import MachineSettings
from models.path import GCodeState, PathSegment

logger = logging.getLogger(__name__)


class GCodeGenerator:
    """Generates optimized GRBL 1.1 G-code with state tracking.

    Attributes:
        settings: Machine-level configuration for clamping and defaults.
    """

    def __init__(self, settings: Optional[MachineSettings] = None) -> None:
        """Initialize G-code generator.

        Args:
            settings: Machine settings. Uses defaults if not provided.
        """
        self.settings = settings or MachineSettings()
        self._state = GCodeState()
        self._commands: List[str] = []
        self._last_element_id: Optional[str] = None

    def reset(self) -> None:
        """Reset generator state and clear all commands."""
        self._state.reset()
        self._commands.clear()
        self._last_element_id = None

    # ------------------------------------------------------------------
    # Header / Footer
    # ------------------------------------------------------------------

    def add_header(self, document_name: str = "") -> None:
        """Add G-code file header per specification.

        Args:
            document_name: Name of the source SVG document.
        """
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        self._commands.extend([
            "; Generated by Inkscape InkBurn extension",
            f"; Document: {document_name}",
            f"; Date: {now}",
            "G21",
            "G90",
        ])

    def add_footer(self) -> None:
        """Add G-code file footer."""
        self._commands.extend([
            "M5",
            "G0 X0 Y0",
            "M2",
        ])

    # ------------------------------------------------------------------
    # Low-level move
    # ------------------------------------------------------------------

    def _format_coord(self, axis: str, value: float) -> str:
        """Format a coordinate value with proper precision.

        Args:
            axis: Axis letter (``X`` or ``Y``).
            value: Coordinate value.

        Returns:
            Formatted axis+value string (e.g. ``X12.34``).
        """
        formatted = f"{value:.{COORD_PRECISION}f}"
        formatted = formatted.rstrip("0").rstrip(".")
        return f"{axis}{formatted}"

    def move_to(
        self,
        point: Vector2d,
        is_cutting: bool = False,
        speed: Optional[int] = None,
        power: Optional[int] = None,
    ) -> None:
        """Add an optimized move command, suppressing redundant parts.

        Args:
            point: Target position.
            is_cutting: Whether this is a cutting move (G1) or travel (G0).
            speed: Feed rate (only emitted for cutting moves).
            power: Laser power S value.
        """
        parts: List[str] = []

        x = round(point.x, COORD_PRECISION)
        y = round(point.y, COORD_PRECISION)

        command = "G1" if is_cutting else "G0"
        if command != self._state.command:
            parts.append(command)
            self._state.command = command

        coords: List[str] = []
        if self._state.x != x:
            coords.append(self._format_coord("X", x))
            self._state.x = x
        if self._state.y != y:
            coords.append(self._format_coord("Y", y))
            self._state.y = y

        if coords:
            parts.extend(coords)
        elif not parts:
            return  # no change at all

        if is_cutting and speed is not None and speed != self._state.speed:
            parts.append(f"F{speed}")
            self._state.speed = speed

        if power is not None and power != self._state.power:
            parts.append(f"S{power}")
            self._state.power = power

        if parts:
            self._commands.append(" ".join(parts))

    def enable_laser(self, mode: str, power: int) -> None:
        """Enable laser mode and associated power 

        Args:
            mode: GRBL laser enable command.
            power: Laser power S value.
        """
        self._commands.append(f"{mode} S{power}")
        self._state.power = power

    # ------------------------------------------------------------------
    # Segment / Job / Layer
    # ------------------------------------------------------------------       
    def add_comment(self, text: str) -> None:
        """Append a G-code comment line.

        Args:
            text: Comment text (without leading semicolon).
        """
        self._commands.append(f"; {text}")

    def add_shape_comment(self, segment: PathSegment) -> None:
        """Add a shape identifier comment when the element changes.

        Args:
            segment: Current path segment.
        """
        if segment.element_id != self._last_element_id:
            comment = f"Shape: {segment.element_type}#{segment.element_id}"
            self.add_comment(comment[:80])
            self._last_element_id = segment.element_id

    def add_segment(self, segment: PathSegment, job: Job) -> None:
        """Add a complete path segment as G-code moves.

        Args:
            segment: Path segment to emit.
            job: Job providing speed/power parameters.
        """
        if not segment.points:
            return

        self.add_shape_comment(segment)

        speed = self.settings.clamp_speed(job.speed)
        power = self.settings.clamp_power(job.power_max)

        # Travel to start
        self.move_to(segment.start_point, is_cutting=False)

        # Enable laser
        self._commands.append(f"{job.laser_mode.value} S{power}")
        self._state.power = power

        # Cut along path
        for point in segment.points[1:]:
            self.move_to(point, is_cutting=True, speed=speed, power=power)

        # Disable laser after segment
        self._commands.append("M5")
        self._state.power = None

    def add_job(
        self,
        segments: List[PathSegment],
        job: Job,
        job_index: int,
    ) -> None:
        """Add all segments for a single job, with multiple passes.

        Args:
            segments: Path segments to process.
            job: Job configuration.
            job_index: Zero-based job index for comments.
        """
        if not job.active:
            return

        passes = max(1, job.passes)
        self._commands.append(
            f"; Job: {job.type.value} {job_index} (id={job.id})"
        )

        for pass_num in range(passes):
            if passes > 1:
                self._commands.append(
                    f"; --- Pass {pass_num + 1}/{passes}"
                )

            self._last_element_id = None

            for segment in segments:
                self.add_segment(segment, job)

    # ------------------------------------------------------------------
    # Output
    # ------------------------------------------------------------------

    def get_gcode(self) -> str:
        """Get complete G-code output as a single string.

        Returns:
            G-code text with newline-separated commands.
        """
        return "\n".join(self._commands) + "\n"
